package npmpackagename

var builtins = map[string]int{
	"assert":         0,
	"buffer":         0,
	"child_process":  0,
	"cluster":        0,
	"console":        0,
	"constants":      0,
	"crypto":         0,
	"dgram":          0,
	"dns":            0,
	"domain":         0,
	"events":         0,
	"fs":             0,
	"http":           0,
	"https":          0,
	"module":         0,
	"net":            0,
	"os":             0,
	"path":           0,
	"punycode":       0,
	"querystring":    0,
	"readline":       0,
	"repl":           0,
	"stream":         0,
	"string_decoder": 0,
	"sys":            0,
	"timers":         0,
	"tls":            0,
	"tty":            0,
	"url":            0,
	"util":           0,
	"vm":             0,
	"zlib":           0,
	// Modules with version lock
	"freelist":       0,
	"v8":             0,
	"process":        0,
	"inspector":      0,
	"async_hooks":    0,
	"http2":          0,
	"perf_hooks":     0,
	"trace_events":   0,
	"worker_threads": 0,
	"node:test":      0,
}
